import sys
import os
sys.path.append(f"/Workspace/Users/mohammedthoufiq9360@gmail.com/Retail-And-Ecommerce-Analytics-Platform")
from src.configs import *

# catalog, schema, volumes names are imported from src/configs file 

INGESTION_PATH=f"/Volumes/{CATALOG_NAME}/{RAW_SCHEMA}/{RAW_VOLUME}/global_fashion"

RAW_CUSTOMERS_PATH=f"/Volumes/{CATALOG_NAME}/{RAW_SCHEMA}/{RAW_VOLUME}/global_fashion/customers.csv"
RAW_DISCOUNTS_PATH=f"/Volumes/{CATALOG_NAME}/{RAW_SCHEMA}/{RAW_VOLUME}/global_fashion/discounts.csv"
RAW_EMPLOYEES_PATH=f"/Volumes/{CATALOG_NAME}/{RAW_SCHEMA}/{RAW_VOLUME}/global_fashion/employees.csv"
RAW_PRODUCTS_PATH=f"/Volumes/{CATALOG_NAME}/{RAW_SCHEMA}/{RAW_VOLUME}/global_fashion/products.csv"
RAW_STORES_PATH=f"/Volumes/{CATALOG_NAME}/{RAW_SCHEMA}/{RAW_VOLUME}/global_fashion/stores.csv"
RAW_TRANSACTIONS_PATH=f"/Volumes/{CATALOG_NAME}/{RAW_SCHEMA}/{RAW_VOLUME}/global_fashion/transactions.csv"


BRONZE_CUSTOMERS_PATH=f"{CATALOG_NAME}.{BRONZE_SCHEMA}.customers"
BRONZE_DISCOUNTS_PATH=f"{CATALOG_NAME}.{BRONZE_SCHEMA}.discounts"
BRONZE_EMPLOYEES_PATH=f"{CATALOG_NAME}.{BRONZE_SCHEMA}.employees"
BRONZE_PRODUCTS_PATH=f"{CATALOG_NAME}.{BRONZE_SCHEMA}.products"
BRONZE_STORES_PATH=f"{CATALOG_NAME}.{BRONZE_SCHEMA}.stores"
BRONZE_TRANSACTIONS_PATH=f"{CATALOG_NAME}.{BRONZE_SCHEMA}.transactions"


SILVER_CUSTOMERS_PATH=f"{CATALOG_NAME}.{SILVER_SCHEMA}.customers"
SILVER_DISCOUNTS_PATH=f"{CATALOG_NAME}.{SILVER_SCHEMA}.discounts"
SILVER_EMPLOYEES_PATH=f"{CATALOG_NAME}.{SILVER_SCHEMA}.employees"
SILVER_PRODUCTS_PATH=f"{CATALOG_NAME}.{SILVER_SCHEMA}.products"
SILVER_STORES_PATH=f"{CATALOG_NAME}.{SILVER_SCHEMA}.stores"
SILVER_TRANSACTIONS_PATH=f"{CATALOG_NAME}.{SILVER_SCHEMA}.transactions"


DIM_CUSTOMERS_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.dim_customers"
DIM_DISCOUNTS_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.dim_discounts"
DIM_EMPLOYEES_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.dim_employees"
DIM_PRODUCTS_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.dim_products"
DIM_STORES_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.dim_stores"
DIM_DATES_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.dim_dates"
FACT_SALES_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.fact_sales"
FACT_RETURNS_PATH=f"{CATALOG_NAME}.{GOLD_SCHEMA}.fact_returns"
